name: CI

on:
  push: {}
  pull_request: {}

jobs:
  ci:
    name: Integration Testing
    runs-on: ubuntu-latest
    steps:
      # checkout code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Install node from package.json volta config
      - name: Install Volta-Node
        uses: volta-cli/action@v1

      # Install packages
      - name: Install NPM Packages
        run: npm ci

      # Lint
      - name: Run ESLint
        run: npm run lint
        env:
          CI: true

      - name: Run Formatting Checkout
        run: npm run format
        env:
          CI: true

      # Tests
      - name: Run Jest Tests
        run: npm run test:ci
        env:
          CI: true
